#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : sundials
Version  : 6.5.0
Release  : 56
URL      : https://github.com/LLNL/sundials/archive/v6.5.0/sundials-6.5.0.tar.gz
Source0  : https://github.com/LLNL/sundials/archive/v6.5.0/sundials-6.5.0.tar.gz
Summary  : Suite of Nonlinear and Differential/ALgebraic equation Solvers
Group    : Development/Tools
License  : BSD-3-Clause
BuildRequires : buildreq-cmake
BuildRequires : cmake
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : openblas
BuildRequires : openmpi-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(PETSc)
BuildRequires : python3
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
SUNDIALS is a family of software packages implemented with the goal of providing
robust time integrators and nonlinear solvers that can easily be incorporated
into existing simulation codes. The primary design goals are to require minimal
information from the user, allow users to easily supply their own data structures
underneath the packages, and allow for easy incorporation of user-supplied linear
solvers and preconditioners.

%prep
%setup -q -n sundials-6.5.0
cd %{_builddir}/sundials-6.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672937847
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz "
%cmake .. -DBUILD_SHARED_LIBS=ON \
-DBUILD_STATIC_LIBS=ON \
-DBUILD_TESTING=ON \
-DMPI_ENABLE=OFF \
-DOPENMP_ENABLE=ON \
-DPTHREAD_ENABLE=ON \
-DF77_INTERFACE_ENABLE=OFF \
-DF2003_INTERFACE_ENABLE=OFF \
-DEXAMPLES_ENABLE_C=ON \
-DEXAMPLES_ENABLE_CXX=ON \
-DEXAMPLES_ENABLE_F90=OFF \
-DEXAMPLES_ENABLE_F77=OFF \
-DEXAMPLES_ENABLE_F2003=OFF \
-DEXAMPLES_INSTALL=ON \
-DEXAMPLES_INSTALL_PATH="/usr/share/sundials/examples" \
-DUSE_GENERIC_MATH=ON
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Ofast -Wl,-z,x86-64-v3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz -march=x86-64-v3 "
export FCFLAGS="$FFLAGS -O3 -Ofast -Wl,-z,x86-64-v3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz -march=x86-64-v3 "
export FFLAGS="$FFLAGS -O3 -Ofast -Wl,-z,x86-64-v3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz -march=x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -O3 -Ofast -Wl,-z,x86-64-v3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz -march=x86-64-v3 "
export CFLAGS="$CFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
%cmake .. -DBUILD_SHARED_LIBS=ON \
-DBUILD_STATIC_LIBS=ON \
-DBUILD_TESTING=ON \
-DMPI_ENABLE=OFF \
-DOPENMP_ENABLE=ON \
-DPTHREAD_ENABLE=ON \
-DF77_INTERFACE_ENABLE=OFF \
-DF2003_INTERFACE_ENABLE=OFF \
-DEXAMPLES_ENABLE_C=ON \
-DEXAMPLES_ENABLE_CXX=ON \
-DEXAMPLES_ENABLE_F90=OFF \
-DEXAMPLES_ENABLE_F77=OFF \
-DEXAMPLES_ENABLE_F2003=OFF \
-DEXAMPLES_INSTALL=ON \
-DEXAMPLES_INSTALL_PATH="/usr/share/sundials/examples" \
-DUSE_GENERIC_MATH=ON
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx512
pushd clr-build-avx512
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Ofast -Wl,-z,x86-64-v4 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz -march=x86_64-v4 -mprefer-vector-width=512 "
export FCFLAGS="$FFLAGS -O3 -Ofast -Wl,-z,x86-64-v4 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz -march=x86_64-v4 -mprefer-vector-width=512 "
export FFLAGS="$FFLAGS -O3 -Ofast -Wl,-z,x86-64-v4 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz -march=x86_64-v4 -mprefer-vector-width=512 "
export CXXFLAGS="$CXXFLAGS -O3 -Ofast -Wl,-z,x86-64-v4 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz -march=x86_64-v4 -mprefer-vector-width=512 "
export CFLAGS="$CFLAGS -march=x86-64-v4 -m64 -Wl,-z,x86-64-v4 -mprefer-vector-width=512"
export CXXFLAGS="$CXXFLAGS -march=x86-64-v4 -m64 -Wl,-z,x86-64-v4 -mprefer-vector-width=512"
export FFLAGS="$FFLAGS -march=x86-64-v4 -m64 -Wl,-z,x86-64-v4 -mprefer-vector-width=512"
export FCFLAGS="$FCFLAGS -march=x86-64-v4 -m64 "
%cmake .. -DBUILD_SHARED_LIBS=ON \
-DBUILD_STATIC_LIBS=ON \
-DBUILD_TESTING=ON \
-DMPI_ENABLE=OFF \
-DOPENMP_ENABLE=ON \
-DPTHREAD_ENABLE=ON \
-DF77_INTERFACE_ENABLE=OFF \
-DF2003_INTERFACE_ENABLE=OFF \
-DEXAMPLES_ENABLE_C=ON \
-DEXAMPLES_ENABLE_CXX=ON \
-DEXAMPLES_ENABLE_F90=OFF \
-DEXAMPLES_ENABLE_F77=OFF \
-DEXAMPLES_ENABLE_F2003=OFF \
-DEXAMPLES_INSTALL=ON \
-DEXAMPLES_INSTALL_PATH="/usr/share/sundials/examples" \
-DUSE_GENERIC_MATH=ON
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pushd clr-build
make test
popd
pushd clr-build-avx2
if grep -q 'avx2[^ ]*' /proc/cpuinfo ; then
    LD_LIBRARY_PATH=%{buildroot}/usr/lib64/glibc-hwcaps/x86-64-v3 make test
fi
popd
pushd clr-build-avx512
if grep -q 'avx512[^ ]*' /proc/cpuinfo ; then
    LD_LIBRARY_PATH=%{buildroot}/usr/lib64/glibc-hwcaps/x86-64-v4 make test
fi
popd

%install
export SOURCE_DATE_EPOCH=1672937847
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sundials
cp %{_builddir}/sundials-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/sundials/b144e8585d2dcb779a70aca47cd777e7ee6af935 || :
cp %{_builddir}/sundials-%{version}/doc/shared/LicenseReleaseNumbers.rst %{buildroot}/usr/share/package-licenses/sundials/ccc5cf5c923b9f8e289174ad71be29bf701f0150 || :
cp %{_builddir}/sundials-%{version}/src/arkode/LICENSE %{buildroot}/usr/share/package-licenses/sundials/b144e8585d2dcb779a70aca47cd777e7ee6af935 || :
cp %{_builddir}/sundials-%{version}/src/cvode/LICENSE %{buildroot}/usr/share/package-licenses/sundials/b144e8585d2dcb779a70aca47cd777e7ee6af935 || :
cp %{_builddir}/sundials-%{version}/src/cvodes/LICENSE %{buildroot}/usr/share/package-licenses/sundials/b144e8585d2dcb779a70aca47cd777e7ee6af935 || :
cp %{_builddir}/sundials-%{version}/src/ida/LICENSE %{buildroot}/usr/share/package-licenses/sundials/b144e8585d2dcb779a70aca47cd777e7ee6af935 || :
cp %{_builddir}/sundials-%{version}/src/idas/LICENSE %{buildroot}/usr/share/package-licenses/sundials/b144e8585d2dcb779a70aca47cd777e7ee6af935 || :
cp %{_builddir}/sundials-%{version}/src/kinsol/LICENSE %{buildroot}/usr/share/package-licenses/sundials/b144e8585d2dcb779a70aca47cd777e7ee6af935 || :
pushd clr-build-avx2
%make_install_v3  || :
popd
pushd clr-build-avx512
%make_install_v4  || :
popd
pushd clr-build
%make_install
popd
## Remove excluded files
rm -f %{buildroot}*/usr/LICENSE
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
